# Uses postgres locally and in production (on Heroku)
#
# Source: www.digitalocean.com/community/tutorials/
#   how-to-set-up-ruby-on-rails-with-postgres

development:
  adapter: postgresql
  encoding: unicode
  database: playground_dev
  pool: 5
  username: williamkrieger
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: playground_test
  pool: 5
  username: williamkrieger
  password: password

# Heroku uses Postgres and fills in the production database info
#
# production:
#   <<: *default
#   database: db/production.sqlite3
